CREATE TABLE `evidenceDetails` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`userEvidenceId` int NOT NULL,
	`evidenceTemplateId` int NOT NULL,
	`evidenceSubTemplateId` int,
	`customFields` text,
	`section1Title` varchar(100),
	`section1Content` text,
	`section2Title` varchar(100),
	`section2Content` text,
	`section3Title` varchar(100),
	`section3Content` text,
	`section4Title` varchar(100),
	`section4Content` text,
	`section5Title` varchar(100),
	`section5Content` text,
	`section6Title` varchar(100),
	`section6Content` text,
	`section7Title` varchar(100),
	`section7Content` text,
	`image1Url` text,
	`image2Url` text,
	`image3Url` text,
	`selectedTheme` varchar(50) NOT NULL DEFAULT 'moe',
	`pdfUrl` text,
	`qrCodeData` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `evidenceDetails_id` PRIMARY KEY(`id`)
);
